In [7]:
# Импортируем библиотеку NumPy
import numpy as np

In [8]:
# 1. Создание массива из обычного списка
my_list = [10, 20, 30, 40, 50]
arr_list = np.array(my_list)

# 2. Создание массива из нулей (3 строки, 4 столбца)
arr_zeros = np.zeros((3, 4))

# 3. Создание массива чисел от 0 до 9 (функция arange)
arr_range = np.arange(10)

print("Массив из списка:", arr_list)
print("Массив нулей:\n", arr_zeros)
print("Массив arange:", arr_range)

Массив из списка: [10 20 30 40 50]
Массив нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив arange: [0 1 2 3 4 5 6 7 8 9]


In [9]:
# Показываем форму и тип данных для массива arr_zeros
print(f"Форма массива (shape): {arr_zeros.shape}") # (3, 4) -> 3 строки, 4 столбца
print(f"Тип данных (dtype): {arr_zeros.dtype}")    # float64

Форма массива (shape): (3, 4)
Тип данных (dtype): float64


In [10]:
# Получение 3-го элемента из arr_list (индексы начинаются с 0)
element = arr_list[2]
print("Третий элемент (индекс 2):", element)

# Срез (извлечение элементов с 1-го по 4-й не включительно)
sub_array = arr_list[1:4]
print("Срез [1:4]:", sub_array)

Третий элемент (индекс 2): 30
Срез [1:4]: [20 30 40]


In [11]:
# Поэлементное умножение массива на 2
arr_mult = arr_list * 2
print("Массив, умноженный на 2:", arr_mult)

# Сложение двух массивов
arr_sum = arr_list + arr_mult
print("Сумма массивов:", arr_sum)

# Вычисление среднего значения (mean)
arr_mean = np.mean(arr_list)
print("Среднее значение:", arr_mean)

# Поиск максимального значения
arr_max = np.max(arr_list)
print("Максимальное значение:", arr_max)

Массив, умноженный на 2: [ 20  40  60  80 100]
Сумма массивов: [ 30  60  90 120 150]
Среднее значение: 30.0
Максимальное значение: 50
